services:
  web:
    build: ./app
    container_name: voting_web
    ports:
      # 8000 is mapped for direct access (bypass WAF)
      # This would be disabled unless penetration testing of the bare app is being performed
      # - bare testing should be done in a separate isolated environment (like this project)
      # - in production this port would be closed to external access
      # - only the WAF port (80) would be exposed externally
      - "8000:8000" 
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      GEO_FILTER_ENABLED: "True"
      GEOIP_DB_PATH: /data/GeoLite2-Country.mmdb
    volumes:
      - ./data:/data
      - ./instance:/instance
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net
      - db_net
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}|{{.ImageName}}|{{.ID}}"

  waf:
    image: owasp/modsecurity-crs:nginx
    container_name: voting_waf
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/waf.conf:/etc/nginx/conf.d/waf.conf:ro
    depends_on:
      - web
    networks:
      - app_net
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}|{{.ImageName}}|{{.ID}}"

  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: voting_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: votingdb
      MYSQL_USER: votinguser
      MYSQL_PASSWORD: votingpass
    volumes:
      - db_data:/var/lib/mysql
      # keep slow query logs on a host path
      # - ./mysql-logs:/var/log/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -prootpass || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      - db_net
    ports:
      - "33306:3306"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.Name}}|{{.ImageName}}|{{.ID}}"

volumes:
  db_data:

networks:
  app_net:
  db_net: